version: "3.8"

services:
  sport-service:
    build: .
    container_name: sport-service
    depends_on:
      - sport-db
    ports:
       - 8080:8080
    environment:
        MYSQL_HOST: sport-db
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_PORT: 3306
  sport-db:
    image: mysql
    container_name: sport-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sport
