spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/test
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  flyway:
    baseline-on-migrate: true
  sql:
    init:
      mode: always

